import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

/**
 * ESLint flat configuration.
 *
 * eslint-config-next v16 ships native flat configs, so they are spread in
 * directly — no FlatCompat shim is needed.
 */
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by `npm test` (tsc output); not source.
      ".test-build/**",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    // Tests run on Node's built-in runner as CommonJS, so `require()` is the
    // correct form there rather than something to be linted away.
    files: ["tests/**/*.js"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
];

export default config;
