import type { Metadata } from "next";
import "./globals.css";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { SHOP, SITE_URL, buildShopJsonLd } from "@/lib/shop";

/**
 * Site-wide metadata. `metadataBase` lets Next resolve the relative OG image
 * path below into an absolute URL, which social platforms require.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SHOP.name} | ${SHOP.nameJa} — 東京・都立家政のパティスリー`,
    template: `%s | ${SHOP.name}`,
  },
  description: SHOP.description,
  openGraph: {
    title: `${SHOP.name} | ${SHOP.nameJa}`,
    description: SHOP.description,
    url: SITE_URL,
    siteName: SHOP.name,
    locale: "ja_JP",
    type: "website",
  },
  robots: { index: true, follow: true },
};

/**
 * Root layout.
 *
 * Injects the shop's structured data once for the whole site rather than
 * per-page. The cart needs no provider here — it is a module-level external
 * store (see lib/cart.tsx), so every component reads the same state.
 *
 * @param children - The active route's page component.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="min-h-screen flex flex-col">
        <script
          type="application/ld+json"
          // Structured data is generated by us from lib/shop.ts — no user
          // input reaches it, so serialising it directly is safe here.
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(buildShopJsonLd()),
          }}
        />
        <SiteHeader />
        <main className="flex-1">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
