// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
// Regenerate with `node scripts/scan-images.mjs`; it also runs automatically
// before `npm run dev` and `npm run build`.
//
// To add a photo, drop a file into public/products/ or public/site/ and
// restart the dev server. Nothing else needs changing.

/** Product photos found on disk, keyed by product ID. */
export const PRODUCT_IMAGES: Record<string, string> = {};

/** Site imagery (hero, about page) found on disk, keyed by filename. */
export const SITE_IMAGES: Record<string, string> = {};
