/**
 * Scans public/products/ and public/site/ and writes lib/images.generated.ts.
 *
 * WHY THIS EXISTS
 * Photography arrives as files, not as code changes. This script means adding
 * a photo is exactly one action — drop the file in the right folder — with no
 * editing of lib/products.ts and no risk of a typo pointing at a file that
 * isn't there.
 *
 * It runs automatically before `npm run dev` and `npm run build` (see the
 * `predev` / `prebuild` scripts in package.json), so a newly added file is
 * picked up on the next start. It is also safe to run by hand:
 *
 *     node scripts/scan-images.mjs
 *
 * The generated file is committed so that a fresh clone type-checks before
 * anything has been built.
 *
 * NAMING
 *   public/products/<product-id>.<ext>   → shown for that product
 *   public/site/<name>.<ext>             → referenced by name in page code
 *
 * Product IDs are the `id` values in lib/products.ts, e.g. `egg-tart-4.jpg`.
 * Recognised extensions: .jpg .jpeg .png .webp .avif
 */

import { readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";

/** Image extensions Next.js can optimise. */
const EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

/**
 * Lists usable images in a public/ subfolder, keyed by filename without
 * extension.
 *
 * @param {string} folder - Path relative to public/, e.g. "products".
 * @returns {Record<string,string>} Map of key to web path.
 */
function scan(folder) {
  const dir = join(process.cwd(), "public", folder);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    return {};
  }

  /** @type {Record<string,string>} */
  const found = {};

  for (const file of readdirSync(dir).sort()) {
    const ext = extname(file).toLowerCase();
    if (!EXTENSIONS.has(ext)) continue;

    const key = basename(file, extname(file));
    // First match wins, so a .jpg and a .webp of the same name are not
    // ambiguous — the alphabetically first extension is used.
    if (!(key in found)) found[key] = `/${folder}/${file}`;
  }

  return found;
}

const products = scan("products");
const site = scan("site");

const contents = `// AUTO-GENERATED by scripts/scan-images.mjs — do not edit by hand.
// Regenerate with \`node scripts/scan-images.mjs\`; it also runs automatically
// before \`npm run dev\` and \`npm run build\`.
//
// To add a photo, drop a file into public/products/ or public/site/ and
// restart the dev server. Nothing else needs changing.

/** Product photos found on disk, keyed by product ID. */
export const PRODUCT_IMAGES: Record<string, string> = ${JSON.stringify(products, null, 2)};

/** Site imagery (hero, about page) found on disk, keyed by filename. */
export const SITE_IMAGES: Record<string, string> = ${JSON.stringify(site, null, 2)};
`;

writeFileSync(join(process.cwd(), "lib", "images.generated.ts"), contents, "utf8");

const total = Object.keys(products).length + Object.keys(site).length;
console.log(
  `[scan-images] ${Object.keys(products).length} product image(s), ` +
    `${Object.keys(site).length} site image(s)` +
    (total === 0 ? " — using placeholders" : ""),
);
